import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
// Bootstrap CSS
import "bootstrap/dist/css/bootstrap.min.css";

//Styles
import "./styles/header.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`container ${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
